# Generated by Django 5.2.7 on 2025-10-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='creador',
        ),
    ]
