# Generated by Django 5.2.7 on 2025-10-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
